// Generated by CoffeeScript 1.10.0
(function() {
  if (window["WebSocket"]) {
    $(document).ready(function() {
      var animate, canvas, connect, context, id, sendDirection, server;
      server = null;
      canvas = $("#stage");
      context = canvas.get(0).getContext("2d");
      id = null;
      sendDirection = function(direction) {
        if (server) {
          return server.send(JSON.stringify({
            'direction': direction
          }));
        }
      };
      animate = function(snakes) {
        var element, i, j, k, len, results, snake, x, y;
        context.fillStyle = 'rgb(230,230,230)';
        for (x = i = 0; i <= 49; x = ++i) {
          for (y = j = 0; j <= 49; y = ++j) {
            context.fillRect(x * 10, y * 10, 9, 9);
          }
        }
        results = [];
        for (k = 0, len = snakes.length; k < len; k++) {
          snake = snakes[k];
          context.fillStyle = snake.id === id ? 'rgb(170,0,0)' : 'rgb(0,0,0)';
          if (snake.id === id) {
            $("#kills").html("Kills: " + snake.kills);
            $("#deaths").html("Deaths: " + snake.deaths);
          }
          results.push((function() {
            var l, len1, ref, results1;
            ref = snake.elements;
            results1 = [];
            for (l = 0, len1 = ref.length; l < len1; l++) {
              element = ref[l];
              x = element[0] * 10;
              y = element[1] * 10;
              results1.push(context.fillRect(x, y, 9, 9));
            }
            return results1;
          })());
        }
        return results;
      };
      connect = function() {
        server = new io.Socket("localhost", {
          'port': 5000
        });
        server.connect();
        return server.on("message", function(event) {
          var message;
          message = JSON.parse(event);
          switch (message.type) {
            case 'id':
              return id = message.value;
            case 'snakes':
              return animate(message.value);
          }
        });
      };
      connect();
      return $(document).keydown(function(event) {
        var key;
        key = event.keyCode ? event.keyCode : event.which;
        switch (key) {
          case 37:
            return sendDirection("left");
          case 38:
            return sendDirection("up");
          case 39:
            return sendDirection("right");
          case 40:
            return sendDirection("down");
        }
      });
    });
  } else {
    alert("Your browser does not support websockets.");
  }

}).call(this);
