// Generated by CoffeeScript 1.10.0
(function() {
  var HOST, PORT, SNAKE_LENGTH, STAGE_HEIGHT, STAGE_WIDTH, Snake, autoClient, checkCollisions, fs, http, io, port, send404, server, snakes, socket, sys, tick, updateState, url, util;

  sys = require('sys');

  http = require('http');

  util = require('util');

  url = require('url');

  io = require('socket.io');

  fs = require('fs');

  HOST = null;

  PORT = 5000;

  STAGE_WIDTH = 49;

  STAGE_HEIGHT = 49;

  SNAKE_LENGTH = 8;

  Array.prototype.remove = function(e) {
    var ref, t;
    if ((t = this.indexOf(e)) > -1) {
      return ([].splice.apply(this, [t, t - t + 1].concat(ref = [])), ref);
    }
  };

  autoClient = 1;

  snakes = [];


  /* Server */

  server = http.createServer(function(req, res) {
    var path;
    path = url.parse(req.url).pathname;
    switch (path) {
      case '/':
      case '/index.html':
      case '/client.js':
      case '/style.css':
        if (path === '/') {
          path = '/index.html';
        }
        return fs.readFile(__dirname + path, function(err, data) {
          if (err) {
            send404(res);
          } else {
            res.writeHead(200, 'text/html');
          }
          res.write(data, 'utf8');
          return res.end();
        });
      default:
        return send404(res);
    }
  });

  send404 = function(res) {
    res.writeHead(404);
    res.write('404');
    return res.end();
  };

  server.listen(port = Number(process.env.PORT || PORT));


  /* Snake Class */

  Snake = (function() {
    function Snake(id) {
      this.id = id;
      this.reset();
      this.kills = 0;
      this.deaths = 0;
    }

    Snake.prototype.addKill = function() {
      this.kills++;
      return this.length = this.elements.unshift([-1, -1]);
    };

    Snake.prototype.reset = function() {
      var i, rH;
      rH = Math.floor(Math.random() * 49);
      this.deaths++;
      this.length = SNAKE_LENGTH;
      this.direction = "right";
      return this.elements = (function() {
        var j, ref, results;
        results = [];
        for (i = j = ref = this.length; ref <= 1 ? j <= 1 : j >= 1; i = ref <= 1 ? ++j : --j) {
          results.push([-i, rH]);
        }
        return results;
      }).call(this);
    };

    Snake.prototype.doStep = function() {
      var i, j, ref;
      for (i = j = 0, ref = this.length - 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        this.moveTail(i);
      }
      return this.moveHead();
    };

    Snake.prototype.moveTail = function(i) {
      this.elements[i][0] = this.elements[i + 1][0];
      return this.elements[i][1] = this.elements[i + 1][1];
    };

    Snake.prototype.moveHead = function() {
      var head;
      head = this.length - 1;
      switch (this.direction) {
        case "left":
          this.elements[head][0] -= 1;
          break;
        case "right":
          this.elements[head][0] += 1;
          break;
        case "up":
          this.elements[head][1] -= 1;
          break;
        case "down":
          this.elements[head][1] += 1;
      }
      if (this.elements[head][0] < 0) {
        this.elements[head][0] = STAGE_WIDTH;
      }
      if (this.elements[head][1] < 0) {
        this.elements[head][1] = STAGE_HEIGHT;
      }
      if (this.elements[head][0] > STAGE_WIDTH) {
        this.elements[head][0] = 0;
      }
      if (this.elements[head][1] > STAGE_HEIGHT) {
        return this.elements[head][1] = 0;
      }
    };

    Snake.prototype.head = function() {
      return this.elements[this.length - 1];
    };

    Snake.prototype.blocks = function(other) {
      var collision, element, head, j, len, ref;
      head = other.head();
      collision = false;
      ref = this.elements;
      for (j = 0, len = ref.length; j < len; j++) {
        element = ref[j];
        if (head[0] === element[0] && head[1] === element[1]) {
          collision = true;
        }
      }
      return collision;
    };

    Snake.prototype.blocksSelf = function() {
      var collision, head, i, j, ref;
      head = this.head();
      collision = false;
      for (i = j = 0, ref = this.length - 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        if (head[0] === this.elements[i][0] && head[1] === this.elements[i][1]) {
          collision = true;
        }
      }
      return collision;
    };

    return Snake;

  })();


  /* Handle Connections */

  socket = io.listen(server);

  socket.on("connection", function(client) {
    var clientId, clientSnake;
    clientId = autoClient;
    clientSnake = new Snake(clientId);
    autoClient += 1;
    snakes.push(clientSnake);
    sys.puts("Client " + clientId + " connected");
    client.send(JSON.stringify({
      type: 'id',
      value: clientId
    }));
    client.on("message", function(message) {
      message = JSON.parse(message);
      return clientSnake.direction = message.direction;
    });
    return client.on("disconnect", function() {
      snakes.remove(clientSnake);
      return sys.puts("Client " + clientId + " disconnected");
    });
  });


  /* Update Game State */

  updateState = function() {
    var j, len, snake;
    for (j = 0, len = snakes.length; j < len; j++) {
      snake = snakes[j];
      snake.doStep();
    }
    checkCollisions();
    return socket.broadcast(JSON.stringify({
      type: 'snakes',
      value: snakes
    }));
  };

  checkCollisions = function() {
    var j, k, l, len, len1, len2, other, resetSnakes, results, snake;
    resetSnakes = [];
    for (j = 0, len = snakes.length; j < len; j++) {
      snake = snakes[j];
      if (snake.blocksSelf()) {
        resetSnakes.push(snake);
      }
      for (k = 0, len1 = snakes.length; k < len1; k++) {
        other = snakes[k];
        if (other !== snake) {
          if (other.blocks(snake)) {
            resetSnakes.push(snake);
            other.addKill();
          }
        }
      }
    }
    results = [];
    for (l = 0, len2 = resetSnakes.length; l < len2; l++) {
      snake = resetSnakes[l];
      results.push(snake.reset());
    }
    return results;
  };

  tick = setInterval(updateState, 100);


  /* Start Server */

  sys.puts("Server running on port " + port);

}).call(this);
